# config/packages/paginator.yaml
knp_paginator:
    page_range: 6                      
    default_options:
        page_name: page                 
        sort_field_name: sort           
        sort_direction_name: direction  
        distinct: true                  
        filter_field_name: filterField  
        filter_value_name: filterValue  
    template:
        pagination: 'parts/pagination/_custom_pagination.html.twig' 