name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  

      - name: Pull latest changes on VPS
        run: |
          ssh -o StrictHostKeyChecking=no root@147.93.55.129 << 'EOF'
            cd /var/www/retro-car-rent/Retro-car-rent
            git pull origin main  
          EOF
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  
