name: Déploiement sur VPS

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Définition des variables d'environnement
        run: |
          echo "APP_ENV=prod" >> $GITHUB_ENV

      - name: Configuration de PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer
          extensions: mbstring, intl, pdo, pdo_mysql

      - name: Installation des dépendances nécessaires pour les tests
        run: composer install --dev --no-interaction

      - name: Exécution des tests unitaires
        run: ./vendor/bin/phpunit --testdox tests/unit

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Configuration de la connexion SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  

      - name: Mise à jour du code sur le VPS
        run: |
          ssh -o StrictHostKeyChecking=no root@147.93.55.129 << 'EOF'
            cd /var/www/retro-car-rent/Retro-car-rent
            git pull origin main
            export APP_ENV=prod
            composer install --no-dev --optimize-autoloader --no-interaction
            php bin/console cache:clear --env=prod
          EOF
